# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\YandexDisk\jojoforever6-1\YandexDisk\2course1term\Practices_and_labs\Knowledge_Representation\my_works\labs\labs\4\new_lab4\guiui\plot.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_plotWindow(object):
    def setupUi(self, plotWindow):
        plotWindow.setObjectName("plotWindow")
        plotWindow.resize(826, 383)
        self.centralwidget = QtWidgets.QWidget(plotWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        plotWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(plotWindow)
        QtCore.QMetaObject.connectSlotsByName(plotWindow)

    def retranslateUi(self, plotWindow):
        _translate = QtCore.QCoreApplication.translate
        plotWindow.setWindowTitle(_translate("plotWindow", "График"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    plotWindow = QtWidgets.QMainWindow()
    ui = Ui_plotWindow()
    ui.setupUi(plotWindow)
    plotWindow.show()
    sys.exit(app.exec_())
